\ProvidesClass{tixtex}[2015/02/12]
\NeedsTeXFormat{LaTeX2e}

\LoadClass[11pt,a4paper]{scrartcl}
\RequirePackage[utf8]{inputenc}
\RequirePackage[T1]{fontenc}
\RequirePackage[english]{babel}

\RequirePackage{xcolor}
\RequirePackage{tikz}

\RequirePackage[bookmarks%
                ,colorlinks=false,pdfborder={0 0 0}%
                ,pdfauthor={Johannes Prem}%
               ]{hyperref}

\setlength{\parindent}{0pt}
\setlength{\parskip}{1.2ex}

\frenchspacing
\pagestyle{empty}
